### ISSUE TITLE
Enabled multithreaded generic algorithm always throws array out of bounds exception

### ISSUE THREAD

**Issue by IncubatedChun** [jMetal/jMetal#125]
I was running the single objective algorithm with multithreaded enabled based on the example from ```ParallelGenerationalGeneticAlgorithmRunner```, however, the exception always happens. Can someone tell what the reason is.  I run the code under java 7 with MBP OX 10.10.3.

>Nov 24, 2015 2:53:14 PM org.uma.jmetal.util.parallel.impl.MultithreadedEvaluator parallelExecution
SEVERE: Error
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at org.uma.jmetal.util.parallel.impl.MultithreadedEvaluator.parallelExecution(MultithreadedEvaluator.java:99)
	at org.uma.jmetal.util.evaluator.impl.MultithreadedSolutionListEvaluator.evaluate(MultithreadedSolutionListEvaluator.java:43)
	at org.uma.jmetal.algorithm.singleobjective.geneticalgorithm.GenerationalGeneticAlgorithm.evaluatePopulation(GenerationalGeneticAlgorithm.java:111)
	at org.uma.jmetal.algorithm.impl.AbstractEvolutionaryAlgorithm.run(AbstractEvolutionaryAlgorithm.java:52)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at java.util.ArrayList.addAll(ArrayList.java:562)
	at prescription.TestProblem.evaluate(TestProblem.java:101)
	at prescription.TestProblem.evaluate(TestProblem.java:1)
	at org.uma.jmetal.util.parallel.impl.MultithreadedEvaluator$EvaluationTask.call(MultithreadedEvaluator.java:139)
	at org.uma.jmetal.util.parallel.impl.MultithreadedEvaluator$EvaluationTask.call(MultithreadedEvaluator.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>	... 1 more

**Comment by matthieu-vergne** [comment]
Which version do you use? Did you try with the current version of the git repo?

**Comment by matthieu-vergne** [comment]
Additionally, do you have an executable code to provide?

**Comment by IncubatedChun** [comment]
@matthieu-vergne  I am using the 5.0 version from the central maven repository.

**Comment by ajnebro** [comment]
I'm running that class in IntelljIdea 15 and it seems to work:

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java -Didea.launcher.port=7533 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 15.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/lib/tools.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Users/ajnebro/Softw/jMetal/jMetal/jmetal-exec/target/classes:/Users/ajnebro/Softw/jMetal/jMetal/jmetal-core/target/classes:/Users/ajnebro/.m2/repository/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar:/Users/ajnebro/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.jar:/Users/ajnebro/.m2/repository/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar:/Users/ajnebro/.m2/repository/org/apache/commons/commons-math3/3.3/commons-math3-3.3.jar:/Users/ajnebro/.m2/repository/org/hamcrest/hamcrest-all/1.3/hamcrest-all-1.3.jar:/Users/ajnebro/Softw/jMetal/jMetal/jmetal-algorithm/target/classes:/Users/ajnebro/Softw/jMetal/jMetal/jmetal-problem/target/classes:/Applications/IntelliJ IDEA 15.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain org.uma.jmetal.runner.singleobjective.ParallelGenerationalGeneticAlgorithmRunner
nov 24, 2015 11:43:26 PM org.uma.jmetal.util.parallel.impl.MultithreadedEvaluator <init>
INFORMACIÓN: THREADS: 8
nov 24, 2015 11:43:26 PM org.uma.jmetal.util.parallel.impl.MultithreadedEvaluator start
INFORMACIÓN: Cores: 8
nov 24, 2015 11:43:26 PM org.uma.jmetal.runner.singleobjective.ParallelGenerationalGeneticAlgorithmRunner main
INFORMACIÓN: Total execution time: 856ms
nov 24, 2015 11:43:26 PM org.uma.jmetal.runner.singleobjective.ParallelGenerationalGeneticAlgorithmRunner main
INFORMACIÓN: Objectives values have been written to file FUN.tsv
nov 24, 2015 11:43:26 PM org.uma.jmetal.runner.singleobjective.ParallelGenerationalGeneticAlgorithmRunner main
INFORMACIÓN: Variables values have been written to file VAR.tsv

Process finished with exit code 0
```
I'm using a MBP with Mac OS X 10.11.1 and JDK 1.8.0_40-ea.

How are you running the program?

**Comment by IncubatedChun** [comment]
@ajnebro @matthieu-vergne  I can run the example class.  However, I did some changes to the code, for example, I applied my own problem and changed the solution type from binary solution to integer solution.  And replaced the crossoverOperator by IntegerSBXCrossover.  Here is my code

```
    Algorithm<IntegerSolution> algorithm;
	Problem problem = p;

	int numberOfCores;

	if (c == null) {
	    numberOfCores = DEFAULT_NUMBER_OF_CORES;
	} else {
	    numberOfCores = c;
	}

	CrossoverOperator<IntegerSolution> crossoverOperator = new IntegerSBXCrossover(
		0.9, 20);
	MutationOperator<IntegerSolution> mutationOperator = new IntegerPolynomialMutation(
		1.0 / 65, 20);
	SelectionOperator<List<IntegerSolution>, IntegerSolution> selectionOperator = new BinaryTournamentSelection<IntegerSolution>();

	GeneticAlgorithmBuilder<IntegerSolution> builder = new GeneticAlgorithmBuilder<IntegerSolution>(
		problem, crossoverOperator, mutationOperator)
		.setPopulationSize(500)
		.setMaxEvaluations(2500)
		.setSelectionOperator(selectionOperator)
		.setSolutionListEvaluator(
			new MultithreadedSolutionListEvaluator<IntegerSolution>(
				numberOfCores, problem));
	algorithm = builder.build();

	AlgorithmRunner algorithmRunner = new AlgorithmRunner.Executor(
		algorithm).execute();
	builder.getEvaluator().shutdown();

	IntegerSolution solution = algorithm.getResult();
	List<IntegerSolution> population = new ArrayList<>(1);
	population.add(solution);
	JMetalLogger.logger.info((new Double(solution.getObjective(0))).toString());
```

**Comment by matthieu-vergne** [comment]
You say you applied your own problem. Can you provide it too? Given the head of the error, I think that the issue comes from `problem.evaluate(solution)`.

**Comment by IncubatedChun** [comment]
Here is the implementation of the `evaluate()`,
``` 
    @Override
    public void evaluate(IntegerSolution arg0) {
	    // Combine the two
	    values = new ArrayList<>();
	    for (int i = 0; i < arg0.getNumberOfVariables(); i++) {
	        values.add(new Double(arg0.getVariableValue(i)));
	    }

	    values.addAll(nonValues);
	    Map<String, String> data = new HashMap<>();
        

        #Some data construction for getting results from restful api
    	String headerString = "";
    	for (Object s : headers) {
	        headerString = headerString + s.toString() + ",";
	    }

	    headerString = headerString.substring(0, headerString.length() - 1);

	    String valueString = "";
	    for (Object v : values) {
	        valueString = valueString + v.toString() + ",";
	    }

	    valueString = valueString.substring(0, valueString.length() - 1);

	    data.put("headers", headerString);
	    data.put("values", valueString);

	    JSONObject obj = new JSONObject(data);
	    RestTemplate rt = new RestTemplate();
	    rt.getMessageConverters().add(new MappingJackson2HttpMessageConverter());
        JSONArray rsp = rt.postForObject("http://127.0.0.1:5000/test", obj, JSONArray.class);
        double objectiveY = (double) ((LinkedHashMap) rsp.get(0)).get("value");
	    arg0.setObjective(0, objectiveY);
    
    }
```

**Comment by matthieu-vergne** [comment]
`prescription.TestProblem.evaluate(TestProblem.java:101)`

Could you tell us which line is the 101?

**Comment by matthieu-vergne** [comment]
I guess it is the `values.addAll(nonValues)`, in which case, we need to know what is your `nonValues`. In short, you have to debug your own code.

**Comment by matthieu-vergne** [comment]
By the way, when you provide a stask trace, provide it as code, otherwise it does not render in a nice way.

**Comment by matthieu-vergne** [comment]
Here look:
```
Nov 24, 2015 2:53:14 PM org.uma.jmetal.util.parallel.impl.MultithreadedEvaluator parallelExecution
SEVERE: Error
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:188)
at org.uma.jmetal.util.parallel.impl.MultithreadedEvaluator.parallelExecution(MultithreadedEvaluator.java:99)
at org.uma.jmetal.util.evaluator.impl.MultithreadedSolutionListEvaluator.evaluate(MultithreadedSolutionListEvaluator.java:43)
at org.uma.jmetal.algorithm.singleobjective.geneticalgorithm.GenerationalGeneticAlgorithm.evaluatePopulation(GenerationalGeneticAlgorithm.java:111)
at org.uma.jmetal.algorithm.impl.AbstractEvolutionaryAlgorithm.run(AbstractEvolutionaryAlgorithm.java:52)
at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ArrayIndexOutOfBoundsException
at java.lang.System.arraycopy(Native Method)
at java.util.ArrayList.addAll(ArrayList.java:562)
at prescription.TestProblem.evaluate(TestProblem.java:101)
at prescription.TestProblem.evaluate(TestProblem.java:1)
at org.uma.jmetal.util.parallel.impl.MultithreadedEvaluator$EvaluationTask.call(MultithreadedEvaluator.java:139)
at org.uma.jmetal.util.parallel.impl.MultithreadedEvaluator$EvaluationTask.call(MultithreadedEvaluator.java:1)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
... 1 more
```
The important thing is the deepest level, which is the `Caused by...` which target your own evaluation method. So try to fix it and it should work properly.

**Comment by IncubatedChun** [comment]
@matthieu-vergne  thanks.
