### ISSUE TITLE
The system cannot find the path specified (\pareto_fronts\ZDT1.pf)

### ISSUE THREAD

**Issue by pwangsom** [jMetal/jMetal#254]
I am a newbie trying to run jMetal 5.

I use Eclipse and import jMetal as the existing maven project.
I get 5 modules of maven project including:
jmetal,
jmetal-core,
jmetal-algorithm,
jmetal-problem,
jmetal-exec

I try to run NSGAIIRunner.java as shown in the document, but I get an error because the system cannot find the path specified (jmetal-problem\src\test\resources\pareto_fronts\ZDT1.pf).

How can I fix it?

The full error log is as follow:

2018-03-22 14:46:33.794 INFO: Loggers configured with null [org.uma.jmetal.util.JMetalLogger configureLoggers]
2018-03-22 14:46:33.913 INFO: Total execution time: 1464ms [org.uma.jmetal.runner.multiobjective.NSGAIIRunner main]
2018-03-22 14:46:33.987 INFO: Random seed: 1521704792254 [org.uma.jmetal.util.AbstractAlgorithmRunner printFinalSolutionSet]
2018-03-22 14:46:33.988 INFO: Objectives values have been written to file FUN.tsv [org.uma.jmetal.util.AbstractAlgorithmRunner printFinalSolutionSet]
2018-03-22 14:46:33.990 INFO: Variables values have been written to file VAR.tsv [org.uma.jmetal.util.AbstractAlgorithmRunner printFinalSolutionSet]
Exception in thread "main" java.io.FileNotFoundException: jmetal-problem\src\test\resources\pareto_fronts\ZDT1.pf (The system cannot find the path specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:196)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:139)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:94)
	at org.uma.jmetal.util.front.imp.ArrayFront.createInputStream(ArrayFront.java:154)
	at org.uma.jmetal.util.front.imp.ArrayFront.<init>(ArrayFront.java:101)
	at org.uma.jmetal.util.AbstractAlgorithmRunner.printQualityIndicators(AbstractAlgorithmRunner.java:54)
	at org.uma.jmetal.runner.multiobjective.NSGAIIRunner.main(NSGAIIRunner.java:84)

**Comment by Juanjdurillo** [comment]
I am not a eclipse user, but if you read the error it is reporting: it
cannot find jmetal-problem\src\test\resources\pareto_fronts\ZDT1.pf, it
indicates that you are executing the software from a working directory
where that file is not accessible (i.e., from that directory that path does
not exist). Change the working directory to a directory where you have
jmetal-problem\src\test\resources\pareto_fronts\ZDT1.pf

2018-03-22 8:56 GMT+01:00 Peerasak Wangsom <notifications@github.com>:

**Comment by pwangsom** [comment]
Thank you for your suggestion.

I edited the relative path to the absolute path of that file.
Now it is worked

Thank you
