### ISSUE TITLE
Runner algorithm problem

### ISSUE THREAD

**Issue by Lassaad-Zaaraoui** [jMetal/jMetal#288]
Hello, 
I install jmetal 5.6 with the correct package hierarchy, but runner errors are triggered during the execution. Indeed they are:
        at org.uma.jmetal.util.JMetalLogger.configureLoggers(JMetalLogger.java:77)
	at org.uma.jmetal.util.JMetalLogger.<clinit>(JMetalLogger.java:39)
	at org.uma.jmetal.runner.multiobjective.NSGAIIRunner.main(NSGAIIRunner.java:76)
Any help please .
best regards

**Comment by matthieu-vergne** [comment]
Surely, the stack trace is incomplete. Please provide all of it.
