### ISSUE TITLE
.dat files and .pf files for WFG and DTLZ

### ISSUE THREAD

**Issue by csgeek95** [jMetal/jMetal#321]
Hello!

I am currently using JMetal 5.1.

It doesn't have .pf files for DTLZ5.4D and DTLZ6.4D (For four objectives).
Similarly, it doesn't have .pf files for DTLZ5.6D and DTLZ6.6D (For six objectives).

Also, there are no .pf files for WFG for 4D and 6D. 

Can someone please guide me how can i have them?
Because i know that Jmetal gives option to GenerateReferenceParetoFront but i am not able to do it!

**Comment by matthieu-vergne** [comment]
I will rely on @ajnebro for this one.

**Comment by csgeek95** [comment]
However, with the reference pareto fronts that are already present, it gives an error in class ComputeQualityIndicators.

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at org.uma.jmetal.util.experiment.component.ComputeQualityIndicators.findBestIndicatorFronts(ComputeQualityIndicators.java:191)
	at org.uma.jmetal.util.experiment.component.ComputeQualityIndicators.run(ComputeQualityIndicators.java:92)
	at org.uma.jmetal.experiment.ZDTScalabilityIStudy.main(ZDTScalabilityIStudy.java:100)



Any and all help will be appreciated.

**Comment by ajnebro** [comment]
These fronts can be generated according to the instructions given in the papers defining them:
* DTLZ: K. Deb, L. Thiele, M. Laumanns, and E. Zitzler, Scalable Test Problems  for  Evolutionary  Multi-Objective  Optimization. Kanpur,  India:
Kanpur  Genetic  Algorithms  Lab.  (KanGAL),  Indian  Inst.  Technol., 2001. KanGAL Report 2 001 001.
* WFG: Simon Huband, Phil Hingston, Luigi Barone, and Lyndon While. A Review of Multi-objective Test Problems and a Scalable Test Problem Toolkit. IEEE Transactions on Evolutionary Computation, volume 10, no 5, pages 477-506. IEEE, October 2006

**Comment by csgeek95** [comment]
Great, thanks! 

Also, can you respond to the above query too?

**Comment by ajnebro** [comment]
Are you using an experiment like this: https://github.com/jMetal/jMetal/blob/master/jmetal-exec/src/main/java/org/uma/jmetal/experiment/DTLZStudy.java ?

**Comment by ajnebro** [comment]
>  Because i know that Jmetal gives option to GenerateReferenceParetoFront but i am not able to do it!

That program is useful to obtain a reference Pareto front from the results of the executions of a set of algorithms solving a same problem; it doesn't produce a true Pareto front.

**Comment by csgeek95** [comment]
> Are you using an experiment like this: https://github.com/jMetal/jMetal/blob/master/jmetal-exec/src/main/java/org/uma/jmetal/experiment/DTLZStudy.java ?

Yes i am. I have edited an experiment class to run instances of DTLZ on a particular algorithm.

**Comment by csgeek95** [comment]
It works for NSGA-II. However, as soon as i switch to MOEA-D with 24 parameters and 5 objectives (generating pareto fronts by invoking GenerateReferenceParetoFront), it doesn't run.

**Comment by csgeek95** [comment]
Thanks for replying!

Yes, you're right and i made sure of that already. 

I have 5 objectives, 1000 population size and am running it for DTLZ1-DTLZ7. The code runs for the first instance but gives error for the second instance while computing the quality indicators in which it gives NoSuchFileException as it fails to create the quality indicator files for the second instance. 

It works perfectly for individual problem instances but when i add all problem instances to be run in one iteration it gives the same error.

**Comment by matthieu-vergne** [comment]
Could you please provide the stack trace of the error?

**Comment by csgeek95** [comment]
Sure i will. 

I am currently running NSGA-III for the same parameters and it is taking ages to run as it creates 1820 reference points. As soon as it gets executed, i will share it right away.
