### ISSUE TITLE
Possible bug in MOMBI2's ranking computation

### ISSUE THREAD

**Issue by nachomsenias** [jMetal/jMetal#326]
Hi there,

I'm working in an algorithmic comparison involving multiple instances of a bi-objective problem. This problem considers both integer and double variables. Some of these instances are failing when running MOMBI2. The exception thrown is always the same:

Exception in thread "main" java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at org.uma.jmetal.util.experiment.component.ExecuteAlgorithms.run(ExecuteAlgorithms.java:41)
	at script.GenericExperimentRunner.main(GenericExperimentRunner.java:89)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:899)
	at java.util.TimSort.mergeAt(TimSort.java:516)
	at java.util.TimSort.mergeCollapse(TimSort.java:441)
	at java.util.TimSort.sort(TimSort.java:245)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1460)
	at java.util.Collections.sort(Collections.java:175)
	at org.uma.jmetal.algorithm.multiobjective.mombi.util.R2RankingNormalized.computeRanking(R2RankingNormalized.java:48)
	at org.uma.jmetal.algorithm.multiobjective.mombi.util.R2RankingNormalized.computeRanking(R2RankingNormalized.java:7)
	at org.uma.jmetal.algorithm.multiobjective.mombi.MOMBI2.computeRanking(MOMBI2.java:127)
	at org.uma.jmetal.algorithm.multiobjective.mombi.MOMBI.replacement(MOMBI.java:52)
	at org.uma.jmetal.algorithm.multiobjective.mombi.AbstractMOMBI.run(AbstractMOMBI.java:138)
	at org.uma.jmetal.util.experiment.util.ExperimentAlgorithm.runAlgorithm(ExperimentAlgorithm.java:75)
	at org.uma.jmetal.util.experiment.component.ExecuteAlgorithms.lambda$run$0(ExecuteAlgorithms.java:41)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	

Regarding the setup of the algorithm, GenericExperimentRunner instances MOMBI2 under the following configuration:

algorithm = new MOMBI2<IntegerDoubleSolution>(
					problemList.get(i).getProblem(),
					generations,
					new IntegerDoubleSBXCrossover(1.0, 5, 							(AbstractIntegerDoubleProblem<IntegerDoubleSolution>) problemList.get(i).getProblem()),
					new IntegerDoublePolynomialMutation(1.0 / problemList.get(i).getProblem().getNumberOfVariables(), 10.0),
					new BinaryTournamentSelection<IntegerDoubleSolution>(),
					new CustomSolutionEvaluator<IntegerDoubleSolution>(measure),
					"mombi2-weights/weight/weight_02D_152.sld"
					);
((MOMBI2<IntegerDoubleSolution>)algorithm).setMaxPopulationSize(populationSize);

Thx for your attention and best regards.

**Comment by matthieu-vergne** [comment]
I did not test anything, but at first sight, it seems to me the contract of `Comparator` is not satisfied. I understand that we don't have a total order of the solutions regarding the attributes used for sorting.

To be more concrete, the code involved seems to be this one in `R2RankingNormalized` :
```java
Collections.sort(population, new Comparator<S>() {
	@Override
	public int compare(S o1, S o2) {
		R2RankingAttribute<S> attribute = new R2RankingAttribute<>();
		R2SolutionData data1 = (R2SolutionData) attribute.getAttribute(o1);
		R2SolutionData data2 = (R2SolutionData) attribute.getAttribute(o2);

		if (data1.alpha < data2.alpha)
			return -1;
		else if (data1.alpha > data2.alpha)
			return 1;
		else
			return 0;
	}
});
```
It might be that we have the same alpha for 2 different solutions (`o1.equals(o2) == false`). Since it is a list, I don't think it should bother it, so another cause might be that actually the order is not preserved. For instance, you reach a time where it find out that `x > y > x`. This might occur if the attributes change during the sorting. In a case of poor concurrency, this might happen.

I would suggest to add a log in this comparator to tell the comparison result of the two solutions it compares. When you have the error, aggregate your logs to check whether you have a loop (i.e. a chain of comparisons which look like `x > ... > x`).

**Comment by nachomsenias** [comment]
Thank you for the early response @matthieu-vergne .

I managed to reduce the number of exceptions thrown by synchronizing the `Collections.sort` block. However, the focus of the concurrency problem is unclear. 

Could it be related with the number of threads executed by `org.uma.jmetal.util.experiment.util.ExperimentAlgorithm.runAlgorithm`?

Is there a way of avoiding the `parallelStream()` for running each algorithmic execution sequentially?

**Comment by matthieu-vergne** [comment]
I think the problem lies in the solutions' attributes, which may evolve during the sorting. Synchronization would probably solve nothing here (maybe reduce, but surely not solve), since we need it on *each* solution during the *whole* sorting process. It would probably solve nothing here since any other piece of code running in parallel which would not synchronize on the solution may threat your processing anyway.

What you could do is move the attribute retrieval out of the sorting, to retrieve everything once and avoid any unexpected change. Something like this :
```java
R2RankingAttribute<S> attribute = new R2RankingAttribute<>();
Map<S, R2SolutionData> dataMap = new HashMap<>();
for(S s : population) {
  dataMap.put(s, (R2SolutionData) attribute.getAttribute(o1));
}
Collections.sort(population, new Comparator<S>() {
        @Override
        public int compare(S o1, S o2) {
          R2SolutionData data1 = dataMap.get(o1);
          R2SolutionData data2 = dataMap.get(o2);

          if (data1.alpha < data2.alpha)
            return -1;
          else if (data1.alpha > data2.alpha)
            return 1;
          else
            return 0;
        }
});
```
If it the bug still occur with this change, then the problem is elsewhere. Otherwise, the problem is confirmed to lie in the concurrency over solution attributes. I would however not use this code as a fix, but rather dig in the design of the experiment.

**Comment by ajnebro** [comment]
Hi @nachomsenias 
  Which version of jMetal are you using? I found a bug in the class running the experiments (all the parallel instaces shared the same algorithm object, what could lead to concurrency errors); it should be fixed in the current version in GitHub.


Antonio

**Comment by nachomsenias** [comment]
Thank you both.
I'm currently using one of the latest builds from jMetal 5.7, specifically the commit on January 29th (9e983d41f3c9f0f079877f77ec21be551b6e7ce2).

With respect to the management of the solutions attribute, taking out the attribute retrieval from the sorting process seems to work for most iterations. However, some individual executions rise NullPointerExceptions when accessing the Map. This could suggest that the Map is modified during the sorting, right?

Exception in thread "main" java.lang.NullPointerException
	at org.uma.jmetal.algorithm.multiobjective.mombi.util.R2RankingNormalized$1.compare(R2RankingNormalized.java:86)
	at org.uma.jmetal.algorithm.multiobjective.mombi.util.R2RankingNormalized$1.compare(R2RankingNormalized.java:1)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1460)
	at java.util.Collections.sort(Collections.java:175)
	at org.uma.jmetal.algorithm.multiobjective.mombi.util.R2RankingNormalized.computeRanking(R2RankingNormalized.java:72)
	at org.uma.jmetal.algorithm.multiobjective.mombi.util.R2RankingNormalized.computeRanking(R2RankingNormalized.java:1)
	at org.uma.jmetal.algorithm.multiobjective.mombi.MOMBI2.computeRanking(MOMBI2.java:127)
	at org.uma.jmetal.algorithm.multiobjective.mombi.MOMBI.replacement(MOMBI.java:52)
	at org.uma.jmetal.algorithm.multiobjective.mombi.AbstractMOMBI.run(AbstractMOMBI.java:138)
	at org.uma.jmetal.util.experiment.util.ExperimentAlgorithm.runAlgorithm(ExperimentAlgorithm.java:75)
	at org.uma.jmetal.util.experiment.component.ExecuteAlgorithms.lambda$0(ExecuteAlgorithms.java:46)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at org.uma.jmetal.util.experiment.component.ExecuteAlgorithms.run(ExecuteAlgorithms.java:46)
	at script.GenericExperimentRunner.main(GenericExperimentRunner.java:94)

Last but not least, I tried to sequentially execute the `ExperimentAlgorithm` list in `ExecuteAlgorithms.run()` instead of using the `parallelStream`. In this case, the execution doesn't rise any errors whatsoever.

**Comment by matthieu-vergne** [comment]
> I'm currently using one of the latest builds from jMetal 5.7, specifically the commit on January 29th ([9e983d4](https://github.com/jMetal/jMetal/commit/9e983d41f3c9f0f079877f77ec21be551b6e7ce2)).

Please use the last one to see if the last fix helps you. If it does, please close this issue. Otherwise, please proceed with the following.

> With respect to the management of the solutions attribute, taking out the attribute retrieval from the sorting process seems to work for most iterations. However, some individual executions rise NullPointerExceptions when accessing the Map. This could suggest that the Map is modified during the sorting, right?

If you use the code I provided, and it does rise NPEs, then it should not be a problem of concurrency on the map. You are using an isolated instance that is fed only once. It should not change anymore.

If the NPE is on a *value* of the map, what may happen is that, when the values were stored, all of them were not yet there, so some of them stored `null`. This may happen if the population attributes are, indeed, changed during the sorting, which is what we may expect. But it would be surprising that the previous error was a broken contract, and not a NPE too.

If the NPE is on a *key* of the map, then it means that the content of the population itself changes during the run (solutions are added, which are not known by the map). In this case, at the very beginning of the `computeRanking` method, start by creating a copy of the population to use everywhere, instead of the original one:
```java
population = new ArrayList<>(population);
```

Please provide your code, so we can figure out which line the exception is referring to when it says:
> Exception in thread "main" java.lang.NullPointerException
> at org.uma.jmetal.algorithm.multiobjective.mombi.util.R2RankingNormalized$1.compare(R2RankingNormalized.java:86)

What you can do is to fork the project, put your modification in your fork, and give us the link to your branch here. This way we can follow your changes and try it ourselves.

> Last but not least, I tried to sequentially execute the `ExperimentAlgorithm` list in `ExecuteAlgorithms.run()` instead of using the `parallelStream`. In this case, the execution doesn't rise any errors whatsoever.

Good to know. It seems to confirm a problem of concurrency.

**Comment by nachomsenias** [comment]
Hi there,

I updated my build to the latest commit and forked the project as instructed. I pushed the map-related code in (75fe9f6d73165e40f992b3a7c464b4670e654527). 

Since I cleaned up the code, the NPE moved to another line in the code: 
`Caused by: java.lang.NullPointerException`
`	at R2RankingNormalized$1.compare(R2RankingNormalized.java:69)`

which corresponds with the access to the objects stored as values in the map:
```java
if (data1.alpha < data2.alpha)
```
However, as previously suggested, I don't know why the previous error was a broken contract and not a NPE aswell.

**Comment by matthieu-vergne** [comment]
Since `alpha` is a double, it cannot be null. By elimination, it is either `data1` or `data2` which is null. Then it appears some solutions miss their `R2RankingAttribute` values at the time we build the map. It is not incompatible with the idea of having concurrent modifications of the solutions.

Could you give the exact list of problems you use? The instances are created through the problem. If the solutions generated are not concurrency-friendly, then it might be the cause.

**Comment by matthieu-vergne** [comment]
Just give one for which the problem occurs. That should be enough.

**Comment by nachomsenias** [comment]
The problem list considers a single custom problem with two objectives employed for model calibration. Thus, each instance has different dimensionality because each instance of the model considers different number of calibration parameters. Specifically, the failing instance considers a single integer decision variable and 99 double decision variables. 

The underlying dependency is not ready to be published yet, but I added code implementing the problem here (c605e1add6089dfef8127918e84c48284513fbc3). Please let me know if you notice anything that could be creating the concurrency problem.

**Comment by matthieu-vergne** [comment]
You can provide everything in a private project. I have a BitBucket account if needed (they provide private repositories).

**Comment by matthieu-vergne** [comment]
Now, be aware that you don't need to provide your actual project. Only to provide a minimal working example where the issue can be reproduced. If it really bothers you to share your stuff, please go for that instead.

**Comment by matthieu-vergne** [comment]
Actually, it would help if we can work on a simpler example. Because you have several dependencies, and who knows where it starts...

**Comment by nachomsenias** [comment]
Hey there,

sorry for taking so long to answer. 

I uploaded a MOMBI2 reduced study using the typical ZDT1 problem instances in #16b8a4b21b843afe53f2e79fcedfa3bd0ff67769 

However, I believe that the error thrown has to do with me misunderstanding how ExperimentAlgorithm works. My bad. 

Just to clarify, I was using a single Algorithm instance for all the ExperimentAlgorithm instances. Any idea why that fact provokes the exceptions? I also included a commented code block that creates a new MOMBI2 instance for each ExperimentAlgorithm object. Since it runs without errors, I guess that was the problem.

I proceed to close the issue, thank you @matthieu-vergne for your feedback.

Cheers.

**Comment by matthieu-vergne** [comment]
Thank you for your feedback.

Indeed, if you use the same algorithm instance for several experiments which run in parallel, then the internal state of the algorithm is read and written in several threads in parallel. Since the algorithm uses a field to store the population, it is almost guaranteed to have concurrency issues.

In general, in Java, try to avoid reusing an instance. Do so only if you have good reasons to (they *must* be equal, etc.). Don't try to save some resources by reducing the number of instances to the minimum. At least don't care about that until you get something working well. Only then you can think about optimization.

Beside that, I'm glad it works now. {^_^}b
