### ISSUE TITLE
PESA2Runner problem

### ISSUE THREAD

**Issue by 420219496** [jMetal/jMetal#358]
good evening! I have a problem when i try to run the PESA2Runner. But i can use other Runner without any problem. The problem is:

Exception in thread "Thread-0" java.lang.NullPointerException
	at org.uma.jmetal.util.AdaptiveGrid.randomOccupiedHypercube(AdaptiveGrid.java:392)
	at org.uma.jmetal.util.AdaptiveGrid.randomOccupiedHypercube(AdaptiveGrid.java:381)
	at org.uma.jmetal.algorithm.multiobjective.pesa2.util.PESA2Selection.execute(PESA2Selection.java:22)
	at org.uma.jmetal.algorithm.multiobjective.pesa2.util.PESA2Selection.execute(PESA2Selection.java:11)
	at org.uma.jmetal.algorithm.multiobjective.pesa2.PESA2.selection(PESA2.java:78)
	at org.uma.jmetal.algorithm.impl.AbstractEvolutionaryAlgorithm.run(AbstractEvolutionaryAlgorithm.java:60)
	at java.lang.Thread.run(Thread.java:748)
2019-07-05 20:58:59.506 信息: Loggers configured with null [org.uma.jmetal.util.JMetalLogger configureLoggers]
2019-07-05 20:58:59.552 信息: Total execution time: 4ms [org.uma.jmetal.runner.multiobjective.PESA2Runner main]
2019-07-05 20:58:59.554 信息: Random seed: 1562331539488 [org.uma.jmetal.util.AbstractAlgorithmRunner printFinalSolutionSet]
2019-07-05 20:58:59.554 信息: Objectives values have been written to file FUN.tsv [org.uma.jmetal.util.AbstractAlgorithmRunner printFinalSolutionSet]
2019-07-05 20:58:59.555 信息: Variables values have been written to file VAR.tsv [org.uma.jmetal.util.AbstractAlgorithmRunner printFinalSolutionSet]
Exception in thread "main" org.uma.jmetal.util.JMetalException: The list of solutions is empty
	at org.uma.jmetal.util.front.imp.ArrayFront.<init>(ArrayFront.java:35)
	at org.uma.jmetal.util.AbstractAlgorithmRunner.printQualityIndicators(AbstractAlgorithmRunner.java:53)
	at org.uma.jmetal.runner.multiobjective.PESA2Runner.main(PESA2Runner.java:76)
Process finished with exit code 1

Thank you!

**Comment by 420219496** [comment]
good evening! ParallelPESA2Runner also has this problem.

**Comment by matthieu-vergne** [comment]
Here is the AdaptiveGrid.java:392:
```java
int rand = randomGenerator.getRandomValue(0, occupied.length - 1);
```
It seems that either the `randomGenerator` is null or the `occupied` is null. Since the first one is provided directly at the level above with `(a, b) -> JMetalRandom.getInstance().nextInt(a, b)` it cannot be null. By elimination this is `occupied` which has not be initialized. For that to happen, it seems that `calculateOccupied()` has never been called.

The debug mode confirms this: the method is never called before and `occupied` is null. Going up in the stack, it seems that this is due to the archive being empty at the start, because the initial population is empty. `createInitialPopulation()` here indeed rely on the max population size, which is set through `setMaxPopulationSize(...)` which is never called by PESA2. Adding `setMaxPopulationSize(populationSize)` in the constructor makes this exception disappear. This is hat is done in other algorithms like ESPEA, so I assume it is a relevant fix.

I suggest @ajnebro to give a look to this, since I am not familiar with this algorithm. Maybe there is something more subtle to the PESA2 case.

**Comment by ajnebro** [comment]
I see. Let me check what is happening. I never use PESA2, but the implementation should work.

**Comment by ajnebro** [comment]
Ok. There was a bug that is fixed now.
