### ISSUE TITLE
NSGA-iii AddPotentialMember Problem

### ISSUE THREAD

**Issue by babylong123** [jMetal/jMetal#360]
hi .
Recently , I use NSGA-iii to reasearch 3-objective functions ...When I finished programming, I found  that NSGA-iii have a problem that is unclear....

When I  excutue (**use the jmetal-exec.src.main.java.org.uma.runner.multiobjective.NSGAIIIRunner Template**) :			
```
			Problem<IntegerSolution> problem;
			Algorithm<List<IntegerSolution>> algorithm;
			CrossoverOperator<IntegerSolution> crossover;
			MutationOperator<IntegerSolution> mutation;
			SelectionOperator<List<IntegerSolution>, IntegerSolution> selection;
			
			String referenceParetoFront = "";  

			problem = ProblemUtils.loadProblem("NSGA.MEC_Experiment");
			//problem = new MEC_Experiment();//
			
			
			double crossoverProbability = 0.9;  
			double crossoverDistributionIndex = 30.0;  
			crossover = new IntegerSBXCrossover(crossoverProbability, crossoverDistributionIndex);  
			 
			double mutationProbability = 1.0 / problem.getNumberOfVariables();  
			double mutationDistributionIndex = 20 ;  
			mutation = new IntegerPolynomialMutation(mutationProbability, mutationDistributionIndex);  
			
			selection = new BinaryTournamentSelection<>();  
			
			
			
			algorithm = new NSGAIIIBuilder<>(problem)
					.setCrossoverOperator(crossover)
					.setMutationOperator(mutation)
					.setSelectionOperator(selection)
					.setMaxIterations(10000)
			        .setPopulationSize(10)
			        .build();
			
//	        algorithm = new NSGAIIBuilder<IntegerSolution>(problem, crossover, mutation)
//	                .setSelectionOperator(selection)
//	                .setMaxEvaluations(3000)
//	                .setPopulationSize(100)
//	                .build();
			
			AlgorithmRunner algorithmRunner = new AlgorithmRunner
							        		.Executor(algorithm)
							        		.execute();
			
			List<IntegerSolution> population = algorithm.getResult();
			long computingTime = algorithmRunner.getComputingTime();  
			
			JMetalLogger.logger.info("Total execution time: " + computingTime + "ms");  
			
		    new SolutionListOutput(population)
                         .setSeparator("\t")
                         .setVarFileOutputContext(new DefaultFileOutputContext("VAR.tsv"))
                         .setFunFileOutputContext(new DefaultFileOutputContext("FUN.tsv"))
                         .print() ;

    JMetalLogger.logger.info("Total execution time: " + computingTime + "ms");
    JMetalLogger.logger.info("Objectives values have been written to file FUN.tsv");
    JMetalLogger.logger.info("Variables values have been written to file VAR.tsv");
```

e.printStackTrace() will print :

**Exception in thread "Thread-1" java.lang.NoClassDefFoundError: org/apache/commons/lang3/tuple/ImmutablePair
	at org.uma.jmetal.algorithm.multiobjective.nsgaiii.util.ReferencePoint.AddPotentialMember(ReferencePoint.java:78)
	at org.uma.jmetal.algorithm.multiobjective.nsgaiii.util.EnvironmentalSelection.associate(EnvironmentalSelection.java:242)
	at org.uma.jmetal.algorithm.multiobjective.nsgaiii.util.EnvironmentalSelection.execute(EnvironmentalSelection.java:313)
	at org.uma.jmetal.algorithm.multiobjective.nsgaiii.NSGAIII.replacement(NSGAIII.java:149)
	at org.uma.jmetal.algorithm.impl.AbstractEvolutionaryAlgorithm.run(AbstractEvolutionaryAlgorithm.java:63)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.tuple.ImmutablePair
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
2019-07-30 10:14:17.607 Message: Total execution time: 247ms [NSGA.MEC_Experiment_Main main]
2019-07-30 10:14:17.616 Message: Total execution time: 247ms [NSGA.MEC_Experiment_Main main]
2019-07-30 10:14:17.616 Message: Objectives values have been written to file FUN.tsv [NSGA.MEC_Experiment_Main main]
2019-07-30 10:14:17.617 Message: Variables values have been written to file VAR.tsv [NSGA.MEC_Experiment_Main main]**

But when I use NSGA-II to excute my model..  The NSGA-II will  completely iterate..
In contrast , NSGA -III just stop at  2 generations.
![image](https://user-images.githubusercontent.com/12405848/62096490-692f2480-b2b6-11e9-8722-f732edb17e33.png)
The variable call ‘index’ counts How many individuals are generated ...

I thought it was my own program at first.. 
 **When I recreate a empty java project, I copied the NSGAIIIRunner template codes and the template problem codes that is called 'DTLZ1' ..It's going to be the same problem (''AddPotentialMember'')as before...Likewise, it stop iterating when the 'index' is equal to 183.** 

I am very confused ..Who can solve my problem? Thanks a lot ....I would appreciate it very much...
(My Jmetal Version is 5.6)

**Comment by babylong123** [comment]
Sorry , I finally found the lack of importing  lang3.jar.....Thanks.
