### ISSUE TITLE
Issue MEOA/ on DTLZ with 3 Objective

### ISSUE THREAD

**Issue by leodsti** [jMetal/jMetal#364]
Hi,

First of all, thank you very much for all the work done on jMetal.
I have run MEOA/D using the provided MOEADRunner.java, however, when trying to use the DTLZ with 3 objectives function I get an exception:

2019-08-21 21:29:10.323 INFO: Loggers configured with null [org.uma.jmetal.util.JMetalLogger configureLoggers]
2019-08-21 21:29:10.359 SEVERE: initializeUniformWeight: failed when reading for file: /W3D_300.dat [org.uma.jmetal.util.JMetalException <init>]
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.uma.jmetal.algorithm.multiobjective.moead.AbstractMOEAD.initializeUniformWeight(AbstractMOEAD.java:111)
	at org.uma.jmetal.algorithm.multiobjective.moead.MOEAD.run(MOEAD.java:46)
	at java.lang.Thread.run(Thread.java:748)

Could you indicate me what is the file "/W3D_300.dat" and how can I get this to work?
Thank in advance,

Regards,

Léo

**Comment by matthieu-vergne** [comment]
It seems that your version of jMetal is not the last one: AbstractMOEAD.java:111 leads to a commented line on the current version. I assume the relevant line now is 118.

Anyway, the runner does not use it, but the builder provides a `setDataDirectory(String)` method to tell where to find this file. Since it is not used, it is initialized to the empty string, so it tries to look for them at the root. The file itself is the one the algorithm expect to find there for 3 objectives with a population size of 300, which should correspond to the setting of your runner. The content is the values used to initialize the `lambda` matrix (which I don't know what it represents since I am not familiar with the algorithm itself). If I am correct, it should contain 300 lines of 3 values separated by spaces or tabs. The values themselves should be doubles (maybe between 0 and 1, not sure).

If you don't want to bother with this file, you can set the algorithm on 2 objectives with 300 or less of population size: it will generate the values automatically.

@ajnebro 
We often receive questions about these files, so I think a section should be added in the documentation for that.

**Comment by leodsti** [comment]
Hi :)
Thanks for your replay.
I have found the option you are mentioning. I have downloaded the data MOEAD_Weights and have indicated the right path to the folder using the .setDataDirectory

I have also updated for to the version 5.9 but sill I am getting the error.

MEOAD
2019-08-21 22:41:11.984 INFO: Loggers configured with null [org.uma.jmetal.util.JMetalLogger configureLoggers]
2019-08-21 22:41:12.020 SEVERE: initializeUniformWeight: failed when reading for file: /Users/leosouquet/MyDocuments/These/Code/Python/MOEAD_Weights/W3D_100.dat [org.uma.jmetal.util.JMetalException <init>]
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.uma.jmetal.algorithm.multiobjective.moead.AbstractMOEAD.initializeUniformWeight(AbstractMOEAD.java:118)
	at org.uma.jmetal.algorithm.multiobjective.moead.MOEAD.run(MOEAD.java:46)
	at java.lang.Thread.run(Thread.java:748)

The population I am looking for is a 100 

    algorithm = new MOEADBuilder(problem, MOEADBuilder.Variant.MOEAD)
            .setCrossover(crossover)
            .setMutation(mutation)
            .setMaxEvaluations(300000)
            .setPopulationSize(100)
            .setResultPopulationSize(100)
            .setNeighborhoodSelectionProbability(0.9)
            .setMaximumNumberOfReplacedSolutions(2)
            .setNeighborSize(20)
            .setFunctionType(AbstractMOEAD.FunctionType.TCHE)
            .setDataDirectory("/Users/leosouquet/MyDocuments/These/Code/Python/MOEAD_Weights")
            .build() ;

This is my builder and still I am getting the same error (the folder /Users/leosouquet/MyDocuments/These/Code/Python/MOEAD_Weights does exists :))

**Comment by leodsti** [comment]
I also have run it with the population 100 on 2 objective function and it works fine but it does not generate anything as when I retry with 3 objective function, it does not work.

**Comment by ajnebro** [comment]
There is a MOEAD3DRunner class. Pleae, could you try to run it?. 

It is configured to solve the LZ09_F6 3D problem with a population of 300 individuals. I've just run it and it works in my laptop, with both a population size of 100 and 300, and also when solving the DTLZ1 problem.
