### ISSUE TITLE
Bug of PESA2

### ISSUE THREAD

**Issue by kelly1208** [jMetal/jMetal#367]
There is a bug with PESA2 when it was used to solve ZDT1 etc.  problem. Details are as follows.
start:
Exception in thread "Thread-0" java.lang.NullPointerException
	at org.uma.jmetal.util.AdaptiveGrid.randomOccupiedHypercube(AdaptiveGrid.java:392)
	at org.uma.jmetal.util.AdaptiveGrid.randomOccupiedHypercube(AdaptiveGrid.java:381)
	at org.uma.jmetal.algorithm.multiobjective.pesa2.util.PESA2Selection.execute(PESA2Selection.java:22)
	at org.uma.jmetal.algorithm.multiobjective.pesa2.util.PESA2Selection.execute(PESA2Selection.java:11)
	at org.uma.jmetal.algorithm.multiobjective.pesa2.PESA2.selection(PESA2.java:78)
	at org.uma.jmetal.algorithm.impl.AbstractEvolutionaryAlgorithm.run(AbstractEvolutionaryAlgorithm.java:65)
	at java.lang.Thread.run(Thread.java:748)
2019-09-15 20:50:36.879 INFO: Loggers configured with null [org.uma.jmetal.util.JMetalLogger configureLoggers]
2019-09-15 20:50:36.926 INFO: Total execution time: 9ms [org.uma.jmetal.runner.multiobjective.PESA2Runner main]
2019-09-15 20:50:36.929 INFO: Random seed: 1568595036840 [org.uma.jmetal.util.AbstractAlgorithmRunner printFinalSolutionSet]
2019-09-15 20:50:36.930 INFO: Objectives values have been written to file FUN.tsv [org.uma.jmetal.util.AbstractAlgorithmRunner printFinalSolutionSet]
2019-09-15 20:50:36.930 INFO: Variables values have been written to file VAR.tsv [org.uma.jmetal.util.AbstractAlgorithmRunner printFinalSolutionSet]
Exception in thread "main" org.uma.jmetal.util.JMetalException: The list of solutions is empty
	at org.uma.jmetal.util.front.imp.ArrayFront.<init>(ArrayFront.java:35)
	at org.uma.jmetal.util.AbstractAlgorithmRunner.printQualityIndicators(AbstractAlgorithmRunner.java:53)
	at org.uma.jmetal.runner.multiobjective.PESA2Runner.main(PESA2Runner.java:76)

Process finished with exit code 1

**Comment by matthieu-vergne** [comment]
I cannot reproduce this error.
Could you please share the code/command you use to run it?

**Comment by mbuzdalov** [comment]
As far as I can see from the current code, this cannot happen assuming the computer works correctly. The latter may be violated if e.g. its memory is faulty, in which conditions everything strange may happen.

Now I try to assume that computer works correctly, the current source code was initially used, but it was subsequently altered.

The error exactly as above may happen if solution evaluator returns an empty list instead of the list of existing solutions. One of the ways to achieve this is to use a custom evaluator, which may filter the list of solutions for certain reasons (e.g. infeasible solutions).

However, as the stack trace says that `PESA2Runner` is printing quality indicators at line 76, which is exactly the same location as in the current version, @kelly1208 did not specify the custom evaluator.

This error is also possible if @kelly1208 altered the PESA2 code instead, at the `evaluatePopulation` method, to modify the `population` variable (again, probably for coping with infeasible solutions). In my opinion, **this is what is happening**, as the stack trace above says that `selection` is called at `PESA2.selection(PESA2.java:78)`, while the vanilla code has it at line 77.

With more analysis, I can conclude that this error can happen only if the initial population is completely wiped out. To reproduce, one may add `population.clear()` at line 65 of vanilla PESA2. @kelly1208, note that there is no legal way to fix the infrastructure around if you leave no chance to it. Even if `AdaptiveGrid` is fixed to handle this issue, the algorithm, at the very basic level of `AbstractEvolutionaryAlgorithm`, will have no idea where to get more individuals if all existing ones are dropped midway.

**Comment by matthieu-vergne** [comment]
@mbuzdalov It might also be that @kelly1208 did not use the last version of the code. It is a good thing to analyse like you do, but we have no guarantee that these are the only possibilities. From my point of view, we currently don't have enough information to figure out anything at this point. Which is why I requested a way to reproduce the bug on our side. Otherwise we might speculate indefinitely.
