### ISSUE TITLE
Problem when running multiple runs of MOEAD

### ISSUE THREAD

**Issue by irfanyounas** [jMetal/jMetal#433]
Hi,
When I try to run MOEAD with more than 1 independent runs, I get the following error:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 357
	at org.uma.jmetal.algorithm.multiobjective.moead.AbstractMOEAD.updateNeighborhood(AbstractMOEAD.java:297)
	at org.uma.jmetal.algorithm.multiobjective.moead.MOEAD.run(MOEAD.java:83)
	at org.uma.jmetal.util.experiment.util.ExperimentAlgorithm.runAlgorithm(ExperimentAlgorithm.java:82)
	at org.uma.jmetal.util.experiment.component.ExecuteAlgorithms.lambda$0(ExecuteAlgorithms.java:56)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at org.uma.jmetal.util.experiment.component.ExecuteAlgorithms.run(ExecuteAlgorithms.java:56)
	at org.uma.jmetal.runner.multiobjective.Main.runExperiment(Main.java:105)
	at org.uma.jmetal.runner.multiobjective.Main.main(Main.java:74)

**Comment by matthieu-vergne** [comment]
Hi,

This stack trace leads to [AbstractMOEAD.java:297](https://github.com/jMetal/jMetal/blob/master/jmetal-algorithm/src/main/java/org/uma/jmetal/algorithm/multiobjective/moead/AbstractMOEAD.java#L297), but this line cannot generate such an exception. I assume you are using a previous version of jMetal.

Could you try the last version?
