### ISSUE TITLE
NullParameterException when using differential evolution

### ISSUE THREAD

**Issue by sitaowang1998** [jMetal/jMetal#438]
I am using the differential evolution to solve a single objective problem on Android, following the example in jmetal-example. When running the program, I got a runtime exception.
```
org.uma.jmetal.util.checking.exception.NullParameterException: The parameter is null
    at org.uma.jmetal.util.checking.Check.isNotNull(Check.java:13)
    at org.uma.jmetal.operator.crossover.impl.DifferentialEvolutionCrossover.bestMutation(DifferentialEvolutionCrossover.java:454)
    at org.uma.jmetal.operator.crossover.impl.DifferentialEvolutionCrossover.mutate(DifferentialEvolutionCrossover.java:432)
    at org.uma.jmetal.operator.crossover.impl.DifferentialEvolutionCrossover.execute(DifferentialEvolutionCrossover.java:289)
    at org.uma.jmetal.algorithm.singleobjective.differentialevolution.DifferentialEvolution.reproduction(DifferentialEvolution.java:97)
    at org.uma.jmetal.algorithm.impl.AbstractEvolutionaryAlgorithm.run(AbstractEvolutionaryAlgorithm.java:61)
    at java.lang.Thread.run(Thread.java:929)
```
I am using algorithm 5.10 from maven central. I also notice the differences in some interfaces between the maven version and the current source code on github, i.e. in maven 5.10 Problem.execute returns void, but this interface has been refactored on github. However, I am not sure if such differences is the cause of the bug.

**Comment by matthieu-vergne** [comment]
5.10 is a year old now. You may try with the current code rather than the maven version. Maybe the bug has been fixed since that time.
