### ISSUE TITLE
Comparison method violates its general contract error appeared with fame algorithm

### ISSUE THREAD

**Issue by MidouDali** [jMetal/jMetal#446]
Hi all,

My question is about the fame algorithm. When I want to use it to resolve dtlz1 problem with populationSize = 100, the program crashes. My Java version is 11.0.12. I assume the cause is that NaN and Infinity values appeared after calling the GenericSolutionAttribute.getAttribute(S solution) method.
this error is outputted:
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeHi(TimSort.java:903)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:520)
	at java.base/java.util.TimSort.mergeForceCollapse(TimSort.java:461)
	at java.base/java.util.TimSort.sort(TimSort.java:254)
	at java.base/java.util.Arrays.sort(Arrays.java:1306)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
	at org.uma.jmetal.algorithm.multiobjective.fame.FAME.addLastRankedSolutionsToPopulation(FAME.java:414)
	at org.uma.jmetal.algorithm.multiobjective.fame.FAME.fast_nondonimated_sort(FAME.java:383)
	at org.uma.jmetal.algorithm.multiobjective.fame.FAME.replacement(FAME.java:370)
	at org.uma.jmetal.algorithm.impl.AbstractEvolutionaryAlgorithm.run(AbstractEvolutionaryAlgorithm.java:62)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by matthieu-vergne** [comment]
Could you please share the jMetal version you are using?
The current FAME class is shorter (line 414 does not exist anymore).

**Comment by AASantiago** [comment]
Try inserting this before sorting the solutions:

System.setProperty("java.util.Arrays.useLegacyMergeSort", "true");

It will use a merge sort instead of the default TrimSort (java issue).
