### ISSUE TITLE
DimensionMismatchException: 4 != 6 with DNSGAII

### ISSUE THREAD

**Issue by MidouDali** [jMetal/jMetal#450]
Hi,
When I test the DNSGAII algorith with the DTLZ1_6D, I get this error:
Exception in thread "Thread-0" org.apache.commons.math3.exception.DimensionMismatchException: 4 != 6
	at org.apache.commons.math3.linear.ArrayRealVector.checkVectorDimensions(ArrayRealVector.java:758)
	at org.apache.commons.math3.linear.ArrayRealVector.dotProduct(ArrayRealVector.java:457)
	at org.apache.commons.math3.linear.RealVector.cosine(RealVector.java:335)
	at org.uma.jmetal.util.solutionattribute.impl.DirScore.computeAngleDistance(DirScore.java:55)
	at org.uma.jmetal.util.solutionattribute.impl.DirScore.computeDirVector(DirScore.java:40)
	at org.uma.jmetal.util.solutionattribute.impl.DirScore.computeDensityEstimator(DirScore.java:25)
	at org.uma.jmetal.operator.selection.impl.RankingAndDirScoreSelection.dirScoreSelection(RankingAndDirScoreSelection.java:61)
	at org.uma.jmetal.operator.selection.impl.RankingAndDirScoreSelection.execute(RankingAndDirScoreSelection.java:48)
	at org.uma.jmetal.algorithm.multiobjective.nsgaii.DNSGAII.replacement(DNSGAII.java:62)
	at org.uma.jmetal.algorithm.impl.AbstractEvolutionaryAlgorithm.run(AbstractEvolutionaryAlgorithm.java:62)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by ajnebro** [comment]
Hi. 
  Class DTLZ1_6D is not in jMetal. Have you implemented it?


Antonio

**Comment by MidouDali** [comment]
Yes, I have implemented it.
Can this negative value be the result of a large number of solutions in the obtained front?

**Comment by ajnebro** [comment]
Sorry for not responding before.

Did you solved your problem?
