### ISSUE TITLE
Constraint on a AbstractIntegerProblem

### ISSUE THREAD

**Issue by Gricel-lee** [jMetal/jMetal#454]
I am trying to add a constraint to my AbstractIntegerProblem. However, it gives me the **error** ```Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0```.

Following https://jmetal.readthedocs.io/en/latest/constraints.html# example ```solution.constraints()[i] = constraint[i]```, I have:

```
public class MRSProblem extends AbstractIntegerProblem {
	
	public MRSProblem() {
		setName("MRS");
		setNumberOfVariables(5);
	        setNumberOfObjectives(3);
		setVariableBounds(lowerBounds,upperBounds); //specified before
	        setNumberOfConstraints(1); 
	}

	public IntegerSolution evaluate(IntegerSolution solution)  {
		solution.objectives()[0] = 10;
		solution.objectives()[1] = 10;
		solution.objectives()[2] = 10;
               // ADDING CONSTRAINT VALUE
                solution.constraints()[0] = 0.5;
}}
```

I can see I have set 1 constraint by printing:
```
System.out.println(problem.getNumberOfConstraints());
```
But nothing is printed when:
```
for (double s: solution.constraints()) {
               System.out.println(s);
}
```

Any ideas? Thank you!

**Comment by matthieu-vergne** [comment]
Can you please share the stack trace of the error? This is what tells us where it is failing exactly.

**Comment by Gricel-lee** [comment]
Thank you for your answer. The error printed is:
```
Exception in thread "Thread-9" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at uoy.mrs.uoy.mrs.auxiliary.jmetal.MRSProblem.evaluate(MRSProblem.java:72)
	at uoy.mrs.uoy.mrs.auxiliary.jmetal.MRSProblem.evaluate(MRSProblem.java:1)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.uma.jmetal.util.evaluator.impl.SequentialSolutionListEvaluator.evaluate(SequentialSolutionListEvaluator.java:17)
	at org.uma.jmetal.algorithm.multiobjective.nsgaii.NSGAII.evaluatePopulation(NSGAII.java:80)
	at org.uma.jmetal.algorithm.impl.AbstractEvolutionaryAlgorithm.run(AbstractEvolutionaryAlgorithm.java:57)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Gricel-lee** [comment]
My algorithm is:
```
public class CallScheduler extends AbstractAlgorithmRunner{
        @SuppressWarnings("rawtypes")
	public static void runner(Allocation a) {
		MRSProblem problem = new MRSProblem(a);
		// crossover
		double crossoverProbability = 0.9;
		double crossoverDistributionIndex = 5.0;
		CrossoverOperator<IntegerSolution> crossover = new IntegerSBXCrossover(crossoverProbability, crossoverDistributionIndex); //CrossoverOperator<DoubleSolution> crossover = new SBXCrossover(crossoverProbability, crossoverDistributionIndex);
		// mutation
		double mutationProbability = 1.0 / problem.getNumberOfVariables();
		double mutationDistributionIndex = 10.0;
		MutationOperator<IntegerSolution> mutation = new IntegerPolynomialMutation(mutationProbability, mutationDistributionIndex);  //MutationOperator<DoubleSolution> mutation = new PolynomialMutation(mutationProbability, mutationDistributionIndex);		
		
		int populationSize = 10;
		int offspringSize = populationSize;
		
		// b) set NSGAII algorithm
		@SuppressWarnings("unchecked")
		Algorithm<List<IntegerSolution>> algorithm = new NSGAII(
											problem,
											Integer.parseInt(Constants.num_evaluations),//maxEvaluations
											populationSize, //populationSize
											Integer.parseInt(Constants.num_population), //matingPoolSize
											offspringSize, //offspringPopulationSize
											crossover, //crossoverOperator
											mutation, //mutationOperator 
											new RandomSelection(), //selectionOperator
											new SequentialSolutionListEvaluator<MRSProblem>() // evaluator
											);
		
		// c) run algorithm
		AlgorithmRunner algorithmRunner = new AlgorithmRunner.Executor(algorithm).execute() ;
		// d) read and save solutions
		List<IntegerSolution> populationSolution = algorithm.getResult() ;
	        long computingTime = algorithmRunner.getComputingTime() ;
	        // - print info
   	        JMetalLogger.logger.info("Total execution time: " + computingTime + "ms");
	        for (IntegerSolution i : populationSolution) {
			System.out.println( i.toString() );
		}
	}
	

}


```


My problem is:
```
public class MRSProblem extends AbstractIntegerProblem {
	/** Constructor */
	public MRSProblem() {
		setName("MRS_");
		setNumberOfVariables(5);
	        setNumberOfObjectives(3);
                // Bounds
                List<Integer> lowerBounds = new ArrayList<Integer>();
	        List<Integer> upperBounds = new ArrayList<Integer>();
                for (int i=0 ; i<5 ; i++) {
			lowerBounds.add(0); 		   // lower bound = 0
			upperBounds.add(10);            // set upper bound as 10 as an example
		}
		setVariableBounds(lowerBounds, upperBounds);
	    setNumberOfConstraints(1);
	}


       public IntegerSolution evaluate(IntegerSolution solution)  {
		// evaluate gene
		double[] res = new double[]{1,2,3};  // fixed for example purposes
		solution.objectives()[0] = res[0];
		solution.objectives()[1] = res[1];
		solution.objectives()[2] = res[2];
		
               
	       // Check later how to avoid solutions with -1 when not schedulable
		double x = 0.65;
		solution.constraints()[0] = x;   // ERROR is HERE -------------------
		return solution;
	  }
}
```
Thank you.

**Comment by ajnebro** [comment]
Hi @Gricel-lee. 
  There is a bug in the `createSolucion()` method of class `AbstractIntegerProblem`. The existing code:

```
  @Override
  public IntegerSolution createSolution() {
    return new DefaultIntegerSolution(getNumberOfObjectives(), getBoundsForVariables());
  }
```
must be replaced by :

```
  @Override
  public IntegerSolution createSolution() {
    return new DefaultIntegerSolution(getNumberOfObjectives(), getNumberOfConstraints(),
        getBoundsForVariables());
  }
```

The bug has been fixed in the proyect hosted in GitHub.

**Comment by Gricel-lee** [comment]
Thank you! That solved the problem, but I am not sure if the solutions are discarded
 when the constraint value is set to -1 (as mentioned in the manual). Thank you again for your answer.

**Comment by ajnebro** [comment]
The solutions are discarded when the constraint value is positive (as the constraints are formulated as ``expression >=0.0``)

**Comment by Gricel-lee** [comment]
Hi,

I have tried both, and it seems that sometimes it returns 1 and others -1:
Variables: ... Objectives: ... Constraints: 1.0 

And some others:
Variables: ... Objectives: ... Constraints: -1.0 

It makes me think is not considering the constraint. Thank you again for your help.

**Comment by ajnebro** [comment]
If you are using NSGA-II, the population can have unfeasible solutions if the number of feasible solutions is lower than the population size. 

You can get feasible solutions by using a sentence similar to this one: 
```
    List<DoubleSolution> population = algorithm.getResult().stream().filter(
        ConstraintHandling::isFeasible).collect(
        Collectors.toList());
```
