### ISSUE TITLE
Wrong number of parents: the remainder if the population size (9) is not divisible by 2

### ISSUE THREAD

**Issue by Gricel-lee** [jMetal/jMetal#455]
I am not sure why I get this Exception from time to time... am I configuring something wrong? Thank you.

```
Exception in thread "Thread-10" org.uma.jmetal.util.errorchecking.JMetalException: Wrong number of parents: the remainder if the population size (9) is not divisible by 2
	at org.uma.jmetal.algorithm.impl.AbstractGeneticAlgorithm.checkNumberOfParents(AbstractGeneticAlgorithm.java:125)
	at org.uma.jmetal.algorithm.multiobjective.nsgaii.NSGAII.reproduction(NSGAII.java:119)
	at org.uma.jmetal.algorithm.impl.AbstractEvolutionaryAlgorithm.run(AbstractEvolutionaryAlgorithm.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
Total execution time: 5ms
```

**Comment by ajnebro** [comment]
Which population size are you using?

**Comment by Gricel-lee** [comment]
Between 9 and 11.
(I have an algorithm to generate them, then I use JMetal to get the Pareto solutions).

Thank you!

**Comment by ajnebro** [comment]
NSGA-II expects a population of even size. 

May I ask you why are you using such population sizes?. They seem rather small to allow a genetic algorithm to make a proper search.

**Comment by Gricel-lee** [comment]
Ok, thank you.

Hi, the population may be bigger, but for this specific scenario is quite small. I am basically using it to select combinations of robots and tasks, so the population depends on the number specified by the user. Regards.
