### ISSUE TITLE
ElitistEvolutionStrategy and NonElitistEvolutionStrategy NullPointerExceptions

### ISSUE THREAD

**Issue by chrstphlbr** [jMetal/jMetal#465]
Hi,

I am using JMetal 6.2 and get NullPointerExceptions when running the algorithms with exceptions similar to this one:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.uma.jmetal.problem.Problem.createSolution()" because the return value of "org.uma.jmetal.algorithm.singl
eobjective.evolutionstrategy.ElitistEvolutionStrategy.getProblem()" is null
        at org.uma.jmetal.algorithm.singleobjective.evolutionstrategy.ElitistEvolutionStrategy.createInitialPopulation(ElitistEvolutionStrategy.java:58)
        at org.uma.jmetal.algorithm.impl.AbstractEvolutionaryAlgorithm.run(AbstractEvolutionaryAlgorithm.java:52)
...
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
        Suppressed: java.lang.NullPointerException: Cannot invoke "org.uma.jmetal.problem.Problem.createSolution()" because the return value of "org.uma.jmetal.algorithm.singleobject
ive.evolutionstrategy.ElitistEvolutionStrategy.getProblem()" is null
                ... 13 more
```

I assume that happens because neither the `ElitistEvolutionStrategy` nor the `NonElitistEvolutionStrategy` constructors set the problem in `AbstractEvolutionaryAlgorithm` but `createInitialPopulation()` and `evaluatePopulation()` call `AbstractEvolutionaryAlgorithm.getProblem()`.

If you need more information, please let me know.

Best wishes,
Christoph

**Comment by ajnebro** [comment]
Dear Christoph.
   What classes are you running? 


Regards,

Antonio

**Comment by ajnebro** [comment]
I have just fixed a bug in the classes implementing the evolution strategies.

**Comment by chrstphlbr** [comment]
Hi Antonio,

I am not sure I understand what you mean by classes that I am running. I can try to give more information:
- I am creating either an `ElitistEvolutionStrategy` or a `NonElitistEvolutionStrategy` with the `EvolutionStrategyBuilder`
- As problem, I am using a `PermutationProblem<PermutationSolution<Int>>` problem which is a subclass of `AbstractIntegerPermutationProblem`
- As mutation operator, I am using a `PermutationSwapMutation`

The code, I am using is available here, in the method starting on line 213: https://github.com/chrstphlbr/bencher/blob/main/src/main/kotlin/ch/uzh/ifi/seal/bencher/prioritization/search/SearchAlgorithms.kt

Best regards,
Christoph

**Comment by ajnebro** [comment]
Creating the evolution strategies using the builders should work now.

**Comment by chrstphlbr** [comment]
Perfect. Thank you!
